resource "aws_key_pair" "server-key" {
  key_name   = "noon"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeiSLTwEfXxNWNWyVPN0wSKi6Fm+6K3vwkK2DGwdXVKC3G31IMBp30IkCnEZoQqzrwoo3KhBKRZQFHzGv7TtTa/uatTl0YO+H5ztYAHioc8QXxnQkExLA7qh+QqSRmrbHKmZo5CHkXDdNDaDynWo9ugQU3nLTvPc7xg84M36s3A3Jg7EzaoOMjKmvmEyGGDfcgXVLUcpOPUywm4jQWOEPMEqCZChD5lyDbl1nBaATAA/KPkccfvVLPTlJLcCTA5cIDQux8kl3+I69HKJlXLosPrL2LO4DIaaWbe10qc8jcPA5UXYYxqqFuK9/wuIxEbWEO9kCduWtqjsY4vQAheyEL appusidhardh@TrollHunters-MacBook-Pro.local"
}
